### ISSUE TITLE
Add a screenshot in the README

### ISSUE THREAD

**Issue by fzaninotto** [vascofg/react-admin-date-inputs#1]
I looked for a conformation that this repo implemented the recommended material-ui design for date pickers... And I didn't find it. 

A simple screenshot embedded in the README would do the trick.

**Comment by vascofg** [comment]
Updated in commit 9737ab23d8da7ca789e4f5d2e220db2d70b64e7e.

**Comment by fzaninotto** [comment]
Excellent, thanks!
