### ISSUE TITLE
label is not taken from resource

### ISSUE THREAD

**Issue by otmi100** [vascofg/react-admin-date-inputs#10]
Hi, 

first of all thanks for your effort!

When I started using your component instead of the original react-admin's DateInput, all labels have disappeared.  Wouldn't it be nice if the basic functions behave the same as in the original component and display the labels based on the ressource field (including the translation)?

I'm using "react-admin-date-inputs": "^1.0.17".

This is my first issue report - if I did something wrong, let me know. I'm willing to learn.

Cheers, 
Mitch

**Comment by vascofg** [comment]
Labels are working on my side, you may need to specify the label prop as I think it's not automatically filled from source field.
If that was what you meant, it may be implemented in the future but just specify the label prop for now.
