### ISSUE TITLE
default use of DateInput with dateFnsUtils results in this broken picker

### ISSUE THREAD

**Issue by zifnab87** [vascofg/react-admin-date-inputs#13]
```
<DateInput source="startDate" options={{ format: 'DD/MM/YYYY' }} />
```

![image](https://user-images.githubusercontent.com/526062/45095015-a0886600-b125-11e8-8ce2-f3e977505406.png)

**Comment by vascofg** [comment]
Can you confirm your date-fns version is exactly "2.0.0-alpha.7"?

**Comment by zifnab87** [comment]
I didn't have any installed - I npm installed that specific version and I still have the same results

**Comment by ashim-k-saha** [comment]
I can solve this by adding `"material-ui-pickers": "1.0.0-rc.13"` in my dependencies.
```
"dependencies": {
    "date-fns": "2.0.0-alpha.7",
    "ra-core": "2.3.0",
    "ra-data-json-server": "2.3.0",
    "ra-language-english": "2.3.0",
    "ra-ui-materialui": "2.3.0",
    "react": "16.3.2",
    "react-admin": "2.3.0",
    "react-admin-date-inputs": "1.0.20",
    "react-dom": "16.3.2",
    "react-scripts": "1.1.4",
    "material-ui-pickers": "1.0.0-rc.13"
}
```

**Comment by vascofg** [comment]
Please try to update to `react-admin-date-inputs@1.1.0`.
Dependencies have been updated to `date-fns@2.0.0-alpha.16` and `material-ui-pickers@1.0.0-rc.14`

**Comment by vascofg** [comment]
Indeed I have, sometimes it takes a while to publish. Please check again,
it's showing up for me.

**Comment by zifnab87** [comment]
@vascofg intresting! My publishes appear right away! Thanks :)

**Comment by afilp** [comment]
@vascofg I updated the library and it works, except of this "initial" strange day numbers:

![image](https://user-images.githubusercontent.com/7850073/45368035-47b84200-b5eb-11e8-8a3d-988d3d85c4e8.png)

If I choose from the calendar, they remain that big, only if I write them directly in the date input as "11" (for example) then they work. The fetches work, despite this UI issue though. Not sure what causes it.

**Comment by afilp** [comment]
I now notice that it works OK if I change the format (which used to work) from:

`options={{format: 'DD/MM/YYYY', showTodayButton: true, keyboard: true}}`

TO:

options={{format: 'dd/MM/YYYY', showTodayButton: true, keyboard: true}}

Is this a changed behavior in latest `date-fns`? Or a bug? 

I would not like to replace all `format` values in my project, but I will do if this is not a bug and is an intended change.

Do you have any idea?

**Comment by vascofg** [comment]
Yes I noticed that too, I think it's a change on date-fns part.

**Comment by afilp** [comment]
There are other problems too, between typing a date and showing it in the calendar:

![image](https://user-images.githubusercontent.com/7850073/45369205-070df800-b5ee-11e8-9396-da6e4983f845.png)

Could it be that something needs to be changed in `react-admin-date-inputs`? Users have problems using it now.
 
Thanks a lot!

**Comment by thecassion** [comment]
For me , I have this error with react-admin v2.3.1 :  
![image](https://user-images.githubusercontent.com/12730875/45887895-c1d68c80-bd8a-11e8-8c17-b2b6b87f7294.png)

**Comment by IgorForkst** [comment]
![screen shot 2018-09-21 at 12 04 33](https://user-images.githubusercontent.com/42277243/45889338-8fcb2780-bd96-11e8-91c3-09c813b53fb8.png)
same error on react admin

**Comment by mcwebb** [comment]
We're also experiencing the UI issue with React Admin v2.3.2.

Is there a incompatibility with MUI?

![screen shot 2018-09-24 at 10 52 19 am](https://user-images.githubusercontent.com/610528/45938871-9b635c00-bfeb-11e8-8cda-d5bbd1efa4a6.png)

**Comment by vascofg** [comment]
You have to provide a material icons font, as explained in
material-ui-pickers docs

**Comment by mcwebb** [comment]
Thank you @vascofg, that was indeed the issue, sorry :)

**Comment by jheiska** [comment]
> @vascofg I updated the library and it works, except of these "initial" strange day numbers:
> 
> ![image](https://user-images.githubusercontent.com/7850073/45368035-47b84200-b5eb-11e8-8a3d-988d3d85c4e8.png)
> 
> If I choose from the calendar, they remain that big, only if I write them directly in the date input as "11" (for example) then they work. The fetches work, despite this UI issue though. Not sure what causes it.

This same issue appears for me, using your version 1.1.2 and the version 2.7.0 of react-admin. Testing it out it seems the number it shows for the day of year that day is. So, if I pick december 31, it shows 365 there. Changing between caps and low-case letters in the format dd/mm/yyyy doesn't seem to make a difference. The date is actually sent correctly, but this can be "slightly" confusing for the user.
