### ISSUE TITLE
Wrong buttons translations

### ISSUE THREAD

**Issue by sorcer1** [vascofg/react-admin-date-inputs#18]
Hello,

In your example [https://material-ui-pickers.firebaseapp.com/localization/moment](https://material-ui-pickers.firebaseapp.com/localization/moment) when you choose fr language the buttons are still in english.

**Comment by lihop** [comment]
@sorcer1 According to [material-ui-picker docs](https://material-ui-pickers.firebaseapp.com/localization/date-fns) the correct import for DateFnsUtils is `@date-io/date-fns`. I changed my import to this and it fixed the problem for me. I have created pull request #19 to update the docs.

**Comment by vascofg** [comment]
merged, thanks for your PR @lihop
