### ISSUE TITLE
Is there a way to translate the name of the month and the week?

### ISSUE THREAD

**Issue by antoniorrm** [vascofg/react-admin-date-inputs#25]

**Comment by hugofialho** [comment]
I'd like too.

**Comment by hugofialho** [comment]
According to readme.md you need pass the providerOptions to the component

import DateFnsUtils from '@date-io/date-fns';
import frLocale from "date-fns/locale/fr";

<DateInput source="date" label="Date in French!" providerOptions={{ utils: DateFnsUtils, locale: frLocale }} />
