### ISSUE TITLE
Validation error is not displayed

### ISSUE THREAD

**Issue by jarradsl** [vascofg/react-admin-date-inputs#5]
Validation error is not displayed when DateInput fails validation. 

          <DateInput
            label="Happened on"
            source="happened_on"
            validate={[required()]}
            options={{
              clearable: true,
              format: 'DD/MM/YYYY',
            }}
          />

The form fails to validate however the Input styling does not change to indicate an error.

**Comment by vascofg** [comment]
Thank you for reporting. Fixed in `1.0.15`.
