### ISSUE TITLE
Internal value for DatePicker has inconsistent time component

### ISSUE THREAD

**Issue by jarradsl** [vascofg/react-admin-date-inputs#6]
Not sure if this is a problem in your component or upstream library but there is inconsistency in DatePicker value behavior.

When setting a value from none to the "Today"/highlighted date, the value becomes a Date with current time components (hours, minutes, seconds). When setting a value to an explicit date (past/future) the value becomes the Date **without** time component (hours/minutes/seconds = 0/0/0).

My opinion is that time components should be 0 when only using DatePicker (aka midnight of the date selected).

**Comment by vascofg** [comment]
This package only wraps the material-ui-pickers components so you should
report this there.

**Comment by jarradsl** [comment]
Created https://github.com/dmtrKovalenko/material-ui-pickers/issues/697
